name: Run Shell Commands
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "This is echo command as part of our first Github Action Workflow file"